# Importar Pandas

In [7]:
#importa pandas
import pandas as pd

# Crear una Serie

In [8]:
# Crea una Serie de los numeros 10, 20 and 10.
serie_numeros = list([10,20,10])

In [9]:
# Crea una Serie con tres objetos: 'rojo', 'verde', 'azul'

serie_color = list(['rojo','verde','azul'])

# Crear un Dataframe

In [10]:
# Crea un dataframe vac√≠o llamado 'df'
df = pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [11]:
# Crea una nueva columna en el dataframe, y asignale la primera serie que has creado
df["numeros"] = serie_numeros
df

   numeros
0       10
1       20
2       10

In [14]:
# Crea otra columna en el dataframe y asignale la segunda Serie que has creado
df["colores"] = serie_color
df

   numeros colores
0       10    rojo
1       20   verde
2       10    azul

# Leer un dataframe

In [36]:
# Lee el archivo llamado 'avengers.csv" localizado en la carpeta "data" y crea un DataFrame, llamado 'avengers'. 
# El archivo est√° localizado en "data/avengers.csv"
avengers = pd.read_csv("/home/carlostr/curso_data_science-master/Secciones/Seccion3.Intro_a_Data_Science/Intro_a_Pandas_ejercicios/data/avengers.csv")
avengers

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

# Inspeccionar un dataframe

In [19]:
# Muestra las primeras 5 filas del DataFrame.
avengers.head(5)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...

In [20]:
# Muestra las primeras 10 filas del DataFrame. 
avengers.head(10)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
5,http://marvel.wikia.com/Richard_Jones_(Earth-616),Richard Milhouse Jones,612,YES,MALE,1963,NaN
6,http://marvel.wikia.com/Steven_Rogers_(Earth-616),Steven Rogers,3458,YES,MALE,1964,Dies at the end of Civil War. Later comes back.
7,http://marvel.wikia.com/Clint_Barton_(Earth-616),Clinton Francis Barton,1456,YES,MALE,1965,Dies in exploding Kree ship in Averngers Vol. ...
8,http://marvel.wikia.com/Pietro_Maximoff_(Earth...,Pietro Maximoff,769,YES,MALE,1965,Dies in House of M Vol 1 Issue 7. Later comes ...
9,http://marvel.wikia.com/Wanda_Maximoff_(Earth-...,Wanda Maximoff,1214,YES,FEMALE,1965,Dies in Uncanny_Avengers_Vol_1_14. Later comes...

In [21]:
# Muestra las √∫ltimas 5 filas del DataFrame.
avengers.tail(5)

,URL,nombre,n_apariciones,actual,genero,fecha_inicio,Notes
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

# Tama√±o del DataFrame

In [22]:
# Muestra el tama√±o del DataFrame
avengers.ndim

2

# Data types en un DataFrame

In [37]:
# Muestra los data types del dataframe
avengers.dtypes

URL              object
nombre           object
n_apariciones     int64
actual           object
genero           object
fecha_inicio      int64
Notes            object
dtype: object

# Editar el indice (index)

In [39]:
# Cambia el indice a la columna "fecha_inicio".
avengers.rename(columns = {'fecha_inicio':'Fecha_de_Inicio'}, inplace = True)
avengers

,URL,nombre,n_apariciones,actual,genero,Fecha_de_Inicio,Notes
0,http://marvel.wikia.com/Henry_Pym_(Earth-616),"Henry Jonathan ""Hank"" Pym",1269,YES,MALE,1963,Merged with Ultron in Rage of Ultron Vol. 1. A...
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
...,...,...,...,...,...,...,...
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN

# Ordenar el indice

In [49]:
# Ordena el √≠ndice de forma descendiente
avengers.sort_index(ascending=False)

,URL,nombre,n_apariciones,actual,genero,Fecha_de_Inicio,Notes
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
...,...,...,...,...,...,...,...
5,http://marvel.wikia.com/Richard_Jones_(Earth-616),Richard Milhouse Jones,612,YES,MALE,1963,NaN
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...

# Resetear el indice

In [50]:
# Resetea el √≠ndice
avengers.reset_index()
avengers

,URL,nombre,n_apariciones,actual,genero,Fecha_de_Inicio,Notes
1,http://marvel.wikia.com/Janet_van_Dyne_(Earth-...,Janet van Dyne,1165,YES,FEMALE,1963,Dies in Secret Invasion V1:I8. Actually was se...
2,http://marvel.wikia.com/Anthony_Stark_(Earth-616),"Anthony Edward ""Tony"" Stark",3068,YES,MALE,1963,"Death: ""Later while under the influence of Imm..."
3,http://marvel.wikia.com/Robert_Bruce_Banner_(E...,Robert Bruce Banner,2089,YES,MALE,1963,"Dies in Ghosts of the Future arc. However ""he ..."
4,http://marvel.wikia.com/Thor_Odinson_(Earth-616),Thor Odinson,2402,YES,MALE,1963,Dies in Fear Itself brought back because that'...
5,http://marvel.wikia.com/Richard_Jones_(Earth-616),Richard Milhouse Jones,612,YES,MALE,1963,NaN
...,...,...,...,...,...,...,...
168,http://marvel.wikia.com/Eric_Brooks_(Earth-616)#,Eric Brooks,198,YES,MALE,2013,NaN
169,http://marvel.wikia.com/Adam_Brashear_(Earth-6...,Adam Brashear,29,YES,MALE,2014,NaN
170,http://marvel.wikia.com/Victor_Alvarez_(Earth-...,Victor Alvarez,45,YES,MALE,2014,NaN
171,http://marvel.wikia.com/Ava_Ayala_(Earth-616)#,Ava Ayala,49,YES,FEMALE,2014,NaN
172,http://marvel.wikia.com/Kaluu_(Earth-616)#,Kaluu,35,YES,MALE,2015,NaN